
spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${PORT}

---
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: false
  config:
    activate:
      on-profile: dev
logging:
  level:
    web: debug
    sql: debug

---

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password:
  jpa:
    show-sql: true
    properties:
      format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  config:
    activate:
      on-profile: test
